# This file contains information about GUI crates and projects in the Rust
# ecosystem.
#
# The allowed keys are as follows:
#
# # A crate on crates.io.
# [crate.my-crate]
# # The name of the crate. Defaults to the crate name, but may be capitalized
# # or named differently if desired.
# name = "MyCrate"
# # Any tags/categories that may be relevant about the crate.
# tags = ["tag1", "tag2"]
# # A description of the crate. Defaults to the description on crates.io.
# description = "A crate to do stuff"
# # Location of the crate's code repository.
# #
# # Defaults to what is specified on crates.io.
# repo = "https://domain.invalid/mycrate/git"
# # Location of the crate's documentation.
# #
# # Defaults to what is specified on crates.io, or otherwise to docs.rs.
# docs = "https://domain.invalid/mycrate/docs"

[crate.gemgui]
name = "GemGui"

[crate.gtk4]
name = "GTK 4"
tags = [
  "gtk",
  "bindings",
]

[crate.rui]
tags = [
  "winit",
  "ios",
  "macos",
  "webgpu",
]

[crate.dominator]
name = "Dominator"

[crate.dioxus]
name = "Dioxus"
description = "Elegant React-like library for building user interfaces for desktop, web, mobile, SSR, liveview, and more."

[crate.gladis]
tags = [
  "gtk",
]

[crate.flutter_rust_bridge]
tags = [
  "bindings",
]

[crate.relm4]
name = "Relm4"
tags = [
  "gtk",
  "bindings",
  "macos",
  "css",
]

[crate.makepad]
name = "Makepad"
repo = "https://github.com/makepad/makepad"
description = "Makepad is a new VR, web and native-rendering UI framework."
tags = [
  "webgpu",
]

[crate.winsafe]
name = "WinSafe"
tags = [
  "bindings",
  "winapi",
]

[crate.fui_core]
name = "fui"
description = "MVVM-oriented (properties, observable collections, bindings), ui! macro, multiplatform, renderer-agnostic, with styles."
docs = "https://github.com/marek-g/rust-fui/blob/master/doc/SUMMARY.md"
tags = [
  "winit",
  "proc-macro",
]

[crate.slint]
name = "Slint"
tags = [
  "proc-macro",
  "winit",
  "embedded",
  "macos",
]

[crate.native-windows-gui]
tags = [
  "bindings",
  "proc-macro",
  "winapi",
]

[crate.iui]
tags = [
  "bindings",
]

[crate.lvgl]
tags = [
  "bindings",
  "embedded",
]

[crate.egui]
tags = [
  "immediate",
]

[crate.imgui]
tags = [
  "bindings",
  "immediate",
]

[crate.tauri]
name = "Tauri"
description = "Tauri is a framework for building tiny, blazing fast binaries for all major desktop platforms."
docs = "https://tauri.studio/en/"
tags = [
  "html",
  "macos",
  "gtk",
]

[crate.vgtk]
tags = [
  "gtk",
]

[crate.conrod-core]
tags = [
  "immediate",
]

[crate.qt_widgets]
description = "Ritual Qt bindings"
docs = "https://rust-qt.github.io/qt/"
tags = [
  "bindings",
  "qt",
]

[crate.fltk]
tags = [
  "bindings",
  "fltk",
]

[crate.kas]
name = "KAS"
tags = [
  "winit",
  "webgpu",
  "proc-macro",
]

[crate.iced]
name = "Iced"
description = "A renderer-agnostic GUI library for Rust focused on simplicity and type-safety. Inspired by Elm."

[crate.core-foundation]
tags = [
  "bindings",
  "macos",
]

[crate.cacao]
tags = [
  "macos",
  "ios",
]

[crate.sciter-rs]
tags = [
  "html",
  "css",
]

[crate.azul]
name = "Azul"
tags = [
  "webrender",
]

[crate.webrender]
name = "WebRender"
tags = [
  "webrender",
]

[crate.druid]
description = "Druid is an experimental Rust-native UI toolkit. Its main goal is to offer a polished user experience. There are many factors to this goal, including performance, a rich palette of interactions (hence a widget library to support them), and playing well with the native platform."
tags = [
  "piet",
]

[crate.orbtk]
name = "OrbTk"
description = "The Orbital Widget Toolkit is a multi platform (G)UI toolkit for building scalable user interfaces with the programming language Rust. It's based on the Entity Component System Pattern and provides a functional-reactive API."

[crate.rust-qt-binding-generator]
tags = [
  "bindings",
  "qt",
  "qml",
]

[crate.qmetaobject]
description = "A framework empowering everyone to create Qt/QML applications with Rust. It does so by building QMetaObjects at compile time, registering QML types (optionally via exposing QQmlExtensionPlugins) and providing idiomatic wrappers."
tags = [
  "proc-macro",
  "bindings",
  "qt",
  "qml",
]

[crate.cxx-qt]
name = "CXX-Qt"
description = "CXX-Qt is a library that automatically generates code to transfer data between Rust and C++ through common interfaces such as QObjects that can be exposed directly into QML. It uses the cxx crate for safe interaction between Rust and C++."
docs = "https://kdab.github.io/cxx-qt/book/"
tags = [
  "bindings",
  "qt",
  "qml",
]

[crate.relm]
tags = [
  "bindings",
  "gtk",
]

[crate.gtk]
name = "GTK 3"
docs = "https://gtk-rs.org/docs-src/"
tags = [
  "bindings",
  "gtk",
]
